### ISSUE TITLE
"Test environment" is alway blank ("") in test runner output

### ISSUE THREAD

**Issue by beccasaurus** [googleapis/sample-tester#119]
My manifest has an `env:`

```yaml
type: manifest/samples
schema_version: 3
base: &common
  bin: 'node'
  env: 'nodejs'
```

But this is the output:

```
RUNNING: Test environment: ""
  RUNNING: Test suite: "Getting word timestamps (Cloud Storage) (LRO)"
    FAILED: Test case: "speech_transcribe_async_word_time_offsets_gcs (no arguments)"
      | 
      | ### Test case SETUP
```

Notice: `Test environment: ""`

I would expect `Test environment: "nodejs"`
