### ISSUE TITLE
bin script with `@args` still appends arguments

### ISSUE THREAD

**Issue by chingor13** [googleapis/sample-tester#131]
For java, we try to run samples through `mvn exec:java` which doesn't allow arbitrary arguments. Thus, the arguments are provided via `-Dexec.args="..."`.

The `@args` is correctly being substituted for the arguments, but the arguments are still being appended to the command causing maven to crash.

```yaml
type: manifest/samples
schema_version: 3
base: &common
  env: 'java'
  bin: 'mvn exec:java -q -D{sample} -Dexec.args="@args"'
  chdir: '{@manifest_dir}/../..'
  basepath: '.'
samples:
- <<: *common
  path: '{basepath}/src/main/java/com/google/cloud/examples/speech/v1/SpeechTranscribeAsyncWordTimeOffsetsGcs.java'
  sample: 'speech_transcribe_async_word_time_offsets_gcs'
```

Example:
```
mvn exec:java -q -Dspeech_transcribe_sync_gcs -Dexec.args="--storage_uri="gs://cloud-samples-data/speech/hello.raw"" ./src/main/java/com/google/cloud/examples/speech/v1/SpeechTranscribeSyncGcs.java --storage_uri="gs://cloud-samples-data/speech/hello.raw"
```
