### ISSUE TITLE
Cannot reconconcile quotes for arguments

### ISSUE THREAD

**Issue by chingor13** [googleapis/sample-tester#132]
* `gen-manifest` quotes the bin command with single-quotes
* command line arguments are quoted with double-quotes

I cannot get the quoting to work for arguments.

```yaml
type: manifest/samples
schema_version: 3
base: &common
  env: 'java'
  bin: 'mvn exec:java -q -D{sample} -Dexec.args="@args"'
  chdir: '{@manifest_dir}/../..'
  basepath: '.'
samples:
- <<: *common
  path: '{basepath}/src/main/java/com/google/cloud/examples/speech/v1/SpeechTranscribeAsyncWordTimeOffsetsGcs.java'
  sample: 'speech_transcribe_async_word_time_offsets_gcs'
```

If I escape the double quotes in the bin command, the args are not replaced in the command.
