### ISSUE TITLE
gen_manifest --flat ignores the first key/value pair

### ISSUE THREAD

**Issue by vchudnov-g** [googleapis/sample-tester#135]
I suspect `--flat` consumes the next arguyment as a value, so in the example below the key `foo` never gets processed:

```
gen-manifest --flat  --foo="foofoo" --bar="barbar" --invocation="echo args='@args'" /tmp/quoted-args/getbook.py 
type: manifest/samples
schema_version: 3
samples:
- bar: barbar
  invocation: echo args='@args'
  path: /tmp/quoted-args/getbook.py
  sample: getbook_sample
```
