### ISSUE TITLE
Assertion failures are not stopping execution of test case

### ISSUE THREAD

**Issue by beccasaurus** [googleapis/sample-tester#3]
Example test: [`reproduce-continue-after-failure.tests.yaml`](https://gist.github.com/beccasaurus/063f163eeaf86970162f91c1ff22e798)

```yaml
# ...
cases:
  - name: Create, List, Delete Company
    spec:

    # List exiting company objects (there should be none)
    - call:
        target: talent_list_companies
        params:
          project_id:
            variable: project_id

    # If "Display name:" is present in the output, this means that the
    # list sample printed out existing companies.
    #
    # I do not want this test to run if there are any companies, it should
    # always have a clean-slate (previous tests cleanup after themselves).
    #
    - assert_not_contains:
      - literal: "Display name:"

    # If the previous assertions failed, this MUST RUN BE EXECUTED.
    - call:
    # ...
```

Expected result:

 - When an assertion fails, the rest of the test does not execute

Actual results:

- When an assertion fails, the rest of the test continues to execute!!

See example output of the example test above:

```
PASSED: Test environment: "nodejs"
  PASSED: Test suite: "Managing Companies (talent v4beta1)"
TEST ERROR CAUGHT!
    FAILED: Test case: "Create, List, Delete Company"
      | 
      | ### Test case SETUP
      | 
      | ### Test case TEST
      | 
      | # Calling: node talent/v4beta1/nodejs/list_companies_request_async_paged_all_talent_list_companies.js --project_id="rebecca-gcp"
      | Company: projects/rebecca-gcp/companies/1a2ddfe9-9c99-41eb-87d2-6249daf4331c
      | Display name: 6ea2aa8b-820e-4e30-9358-d5840297b467
      | External ID: 6ea2aa8b-820e-4e30-9358-d5840297b467
      | Company: projects/rebecca-gcp/companies/2865eed5-0c03-408a-b63f-c194e5975df7
      | Display name: My company
      | External ID: Identifier of this company in my system
      | Company: projects/rebecca-gcp/companies/347a4ae3-13e1-4150-b600-62cf12f31f50
      | Display name: 37a0dcbe-7ff8-44a0-be61-c42ac4e96c6a
      | External ID: 37a0dcbe-7ff8-44a0-be61-c42ac4e96c6a
      | Company: projects/rebecca-gcp/companies/692f6493-4a39-4ab6-9739-74475a9ea7c6
      | Display name: be0e1540-4ed4-42c3-8f2e-6eea2fda815b
      | External ID: be0e1540-4ed4-42c3-8f2e-6eea2fda815b
      | # FAILED ASSERTION: required "Display name:" absent in preceding output
      | 
      | # Calling: node talent/v4beta1/nodejs/create_company_request_talent_create_company.js --display_name="3f560008-e01b-41d6-83dd-ffc3d5652e19" --external_id="3f560008-e01b-41d6-83dd-ffc3d5652e19" --project_id="rebecca-gcp"
      | Created company: 3f560008-e01b-41d6-83dd-ffc3d5652e19
      | Company name: projects/rebecca-gcp/companies/36b8c745-b0e6-4935-8db9-faaab7e22e6b
      | 
      | ### Test case TEARDOWN
      | 

Tests failed
```

Note, after `FAILED ASSERTION` there is another `call:` executed (the test case should have stopped executing)
