### ISSUE TITLE
[Feature Request] assert_contains_one_of

### ISSUE THREAD

**Issue by beccasaurus** [googleapis/sample-tester#54]
We often need to assert that the output includes ONE OF multiple options. Rather than ALL OF.

We could have:

```yaml
assert_contains_all:

assert_contains_one_of:

# alias for assert_contains_all:
assert_contains:
```

Regardless of `assert_contains:` ~ just having `assert_contains_one_of:` will unblock some of our tests from providing higher quality, more accurate sample verification.

### Why?

Some of the APIs return results which are not deterministic (think ML models)

But it's reasonable to assert that one of a number of items MUST be in the result output.
