### ISSUE TITLE
Add `required: true` option to `env:` to fail when variable missing

### ISSUE THREAD

**Issue by beccasaurus** [googleapis/sample-tester#84]
Request: Add `required: true` option to `env:` to fail when variable missing

```yaml
- env:
    name: THE_VAR
    variable: the_var
    required: true
    message: "Required for blah" # optional. Error would include both the name (THE_VAR) and this message
```

> Required environment variable unset: THE_VAR
> Required for blah
