### ISSUE TITLE
[BUG] Case runs if EXCEPTION raised in setup block

### ISSUE THREAD

**Issue by beccasaurus** [googleapis/sample-tester#85]
I added a log statement to my case: `"LOG FROM THE CASE, which ran"`

Here's the sample-tester output:
```
RUNNING: Test environment: "python"
  RUNNING: Test suite: "AutoML Video Object Tracking – Dataset Management"
    SKIPPED: Test case: "Import Data"
  RUNNING: Test suite: "AutoML Video Object Tracking – Model Tests"
    FAILED: Test case: "List Models"
      | 
      | ### Test case SETUP
      | # EXCEPTION!! KeyError('AUTOML_MODEL_ID_x_VIDEO_OT',)
      | 
      | ### Test case TEST
      | LOG FROM THE CASE, which ran
      | # FAILED ASSERTION: required, but did not find, all of the following values in the preceding output: ('FAIL',)
      | 
      | ### Test case TEARDOWN
      | 
    SKIPPED: Test case: "Get Model"
    SKIPPED: Test case: "List and Get Model Evaluations"

Tests failed
```

**Comment by beccasaurus** [comment]
Simpler reproduction case:
```yaml
test:
  suites:
  - name: AutoML Video Object Tracking – Model Tests
    setup:
    - assert_contains:
      - literal: FAIL
    cases:
    - name: List Models
      spec:
      - log: ["LOG FROM THE CASE, which ran"]
      - assert_contains:
        - literal: FAIL
```

```
RUNNING: Test environment: "python"
  RUNNING: Test suite: "AutoML Video Object Tracking – Dataset Management"
    SKIPPED: Test case: "Import Data"
  RUNNING: Test suite: "AutoML Video Object Tracking – Model Tests"
    FAILED: Test case: "List Models"
      | 
      | ### Test case SETUP
      | # FAILED ASSERTION: required, but did not find, all of the following values in the preceding output: ('FAIL',)
      | 
      | ### Test case TEST
      | LOG FROM THE CASE, which ran
      | # FAILED ASSERTION: required, but did not find, all of the following values in the preceding output: ('FAIL',)
      | 
      | ### Test case TEARDOWN
      | 
    SKIPPED: Test case: "Get Model"
    SKIPPED: Test case: "List and Get Model Evaluations"

Tests failed
```

**Comment by beccasaurus** [comment]
Another simple example:
```yaml
est:
  suites:
  - name: Reproduce Bug

    setup:
    - code: |
        assert_that("MISSING_ENV_VAR" in os.environ,
        "Missing required environment variable: MISSING_ENV_VAR")

    cases:
    - name: A Test Case
      spec:
      - code: |
          assert_that("MISSING_ENV_VAR" in os.environ,
          "Missing required environment variable: MISSING_ENV_VAR")
```
```
RUNNING: Test environment: "python"
  RUNNING: Test suite: "Reproduce Bug"
    FAILED: Test case: "A Test Case"
      | 
      | ### Test case SETUP
      | # FAILED ASSERTION: Missing required environment variable: MISSING_ENV_VAR
      | 
      | ### Test case TEST
      | # FAILED ASSERTION: Missing required environment variable: MISSING_ENV_VAR
      | 
      | ### Test case TEARDOWN
      | 

Tests failed
```

I have to duplicate my assertions in setup + in each test case today to workaround this
