### ISSUE TITLE
Passing --chdir="{@manifest_dir}/.." does not work (it requires an extra set of quotes)

### ISSUE THREAD

**Issue by beccasaurus** [googleapis/sample-tester#89]
Passing --chdir="{@manifest_dir}/.." does not work (it requires an extra set of quotes)

To get gen-manifest to work, I had to do this instead:

```
--chdir="'{@manifest_dir}/..'"
```

This is surprising. Can we fix this?

----

#### Original problem:

I tried the new `@manifest_dir` but I get an error when I try to run the tests:

```
ERROR: could not run tests because could not create test environments for convention "tag": ScannerError('while scanning for the next token', None, 
"found character '@' that cannot start any token", <yaml.error.Mark object at 0x1071b0cc0>)
```

My manifest.yaml
```yaml
type: manifest/samples
schema_version: 3
base: &common
  chdir: @manifest_dir
samples:
- <<: *common
  path: samples/v1beta1/automl_video_object_tracking_batch_predict.py
  sample: automl_video_object_tracking_batch_predict
- <<: *common
  path: samples/v1beta1/automl_video_object_tracking_cancel_operation.py
  sample: automl_video_object_tracking_cancel_operation
- <<: *common
  path: samples/v1beta1/automl_video_object_tracking_create_dataset.py
  sample: automl_video_object_tracking_create_dataset
- <<: *common
  path: samples/v1beta1/automl_video_object_tracking_create_model.py
  sample: automl_video_object_tracking_create_model
# ...
```

**Comment by beccasaurus** [comment]
I tried schema 2 and it doesn't work for me either:

Test output:
```
$ sample-tester --cases "List Models" samples/*/test/*
/Users/rebeccataylor/.pyenv/versions/3.6.8/lib/python3.6/site-packages/sampletester/sample_manifest.py:557: YAMLLoadWarning: calling yaml.load_all() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  for manifest in yaml.load_all(data):
RUNNING: Test environment: ""
  RUNNING: Test suite: "AutoML Video Object Tracking – Dataset Management"
    SKIPPED: Test case: "Import Data"
  RUNNING: Test suite: "AutoML Video Object Tracking – Model Tests"
    SKIPPED: Test case: "Create Model (and then cancel creation)"
    FAILED: Test case: "List Models"
      | 
      | ### Test case SETUP
      | 
      | ### Test case TEST
      | 
      | # Calling: /Users/rebeccataylor/code/beccasaurus/google-cloud-python/automl/samples/v1beta1/automl_video_object_tracking_list_models.py --project="rebecca-test-video-automl-ot"
      | # EXCEPTION!! FileNotFoundError(2, "No such file or directory: '@manifest_dir'")
```

^--- `# EXCEPTION!! FileNotFoundError(2, "No such file or directory: '@manifest_dir'")`

Manifest:
```yaml
version: 2
sets:
- chdir: '@manifest_dir'
  path: /Users/rebeccataylor/code/beccasaurus/google-cloud-python/automl/
  __items__:
  - path: samples/v1beta1/automl_video_object_tracking_batch_predict.py
    sample: automl_video_object_tracking_batch_predict
  - path: samples/v1beta1/automl_video_object_tracking_cancel_operation.py
    sample: automl_video_object_tracking_cancel_operation
  - path: samples/v1beta1/automl_video_object_tracking_create_dataset.py
    sample: automl_video_object_tracking_create_dataset
  - path: samples/v1beta1/automl_video_object_tracking_create_model.py
    sample: automl_video_object_tracking_create_model
  - path: samples/v1beta1/automl_video_object_tracking_delete_dataset.py
    sample: automl_video_object_tracking_delete_dataset
# ...
```
